apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blackbox.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blackbox.labels" . | nindent 4 }}
data:
  config.yml: |
{{- toYaml .Values.server.config | nindent 4 }}


