apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: monitoring
data:
  haproxy.cfg: |
    global
        ulimit-n 500000
        maxconn 99999
        maxpipes 99999
        tune.maxaccept 500
        log /dev/log local0
        log /dev/log local1 notice
        chroot /var/lib/haproxy
        stats socket /var/lib/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/certs

        # Default ciphers to use on SSL-enabled listening sockets
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

    defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

    frontend stats
        bind *:8404
        stats enable
        stats uri /stats
        stats refresh 10s
        stats admin if TRUE

    frontend frontend 
        bind *:80
        bind *:443 ssl crt /etc/ssl/private/live/canopy.nodefleet.net/canopy.pem.key

        # BEGIN CORS
        http-response set-header Access-Control-Allow-Origin "*"
        http-response set-header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization, JSNLog-RequestId, activityId, applicationId, applicationUserId, channelId, senderId, sessionId"
        http-response set-header Access-Control-Max-Age 3628800
        http-response set-header Access-Control-Allow-Methods "GET, DELETE, OPTIONS, POST, PUT"

        # Canopy Node Services
        acl is_canopy_wallet hdr(host) -i wallet.canopy.nodefleet.net
        use_backend canopy_wallet_backend if is_canopy_wallet

        acl is_canopy_explorer hdr(host) -i explorer.canopy.nodefleet.net
        use_backend canopy_explorer_backend if is_canopy_explorer

        acl is_canopy_rpc hdr(host) -i rpc.canopy.nodefleet.net
        use_backend canopy_rpc_backend if is_canopy_rpc

        acl is_canopy_adminrpc hdr(host) -i adminrpc.canopy.nodefleet.net
        use_backend canopy_adminrpc_backend if is_canopy_adminrpc

    frontend frontend_grafana
        bind *:80
        bind *:443 ssl crt /etc/ssl/private/live/canopy.nodefleet.net/canopy.pem.key

        acl is_grafana hdr(host) -i monitoring.canopy.nodefleet.net
        use_backend grafana_backend if is_grafana

    # Grafana backend
    backend grafana_backend
        mode http
        option httpchk GET /api/health
        http-check expect status 200
        server grafana grafana.monitoring.svc.cluster.local:3000 check

    # Canopy backends
    backend canopy_wallet_backend
        mode http
        acl auth_ok http_auth(users)
        http-request auth realm "Protected Area" if !auth_ok
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        http-response set-header Access-Control-Allow-Origin *
        http-response set-header Access-Control-Allow-Methods "GET, POST, OPTIONS"
        http-response set-header Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
        http-response set-header Access-Control-Allow-Credentials true
        server canopy_wallet canopy-node.canopy.svc.cluster.local:50000

    backend canopy_explorer_backend
        mode http
        acl auth_ok http_auth(users)
        http-request auth realm "Protected Area" if !auth_ok
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        http-response set-header Access-Control-Allow-Origin *
        http-response set-header Access-Control-Allow-Methods "GET, POST, OPTIONS"
        http-response set-header Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
        http-response set-header Access-Control-Allow-Credentials true
        server canopy_explorer canopy-node.canopy.svc.cluster.local:50001

    backend canopy_rpc_backend
        mode http
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        http-response set-header Access-Control-Allow-Origin *
        http-response set-header Access-Control-Allow-Methods "GET, POST, OPTIONS"
        http-response set-header Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
        http-response set-header Access-Control-Allow-Credentials true
        server canopy_rpc canopy-node.canopy.svc.cluster.local:50002

    backend canopy_adminrpc_backend
        mode http
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        http-response set-header Access-Control-Allow-Origin *
        http-response set-header Access-Control-Allow-Methods "GET, POST, OPTIONS"
        http-response set-header Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
        http-response set-header Access-Control-Allow-Credentials true
        server canopy_adminrpc canopy-node.canopy.svc.cluster.local:50003

    # User list for basic authentication
    userlist users
        user canopy password $6$yaAJwFRSPYp.b/b5$2HtxZgZ.0r4Oz9MSQwBpx3RgAOJ/x9Fa1h/uuH3aSo2IPl.OFmdRcMo1jg37jG3LHDDqjhgfTDnrHK2KhtGf6. 