apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promtail.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
data:
  promtail.yaml: |
    {{- toYaml .Values.promtail.config | nindent 4 }}

